// ============================================================
// 시드 주류 카탈로그 — Phase 1 검색/위시리스트 시연용 글로벌 DB.
// status='approved' 로 미리 등록되어 있다고 가정.
// ============================================================

import type { Drink } from "@/types";

const now = "2026-05-01T00:00:00.000Z";

function d(partial: Omit<Drink, "data_source" | "status" | "created_at">): Drink {
  return {
    data_source: "public_db",
    status: "approved",
    created_at: now,
    ...partial,
  };
}

export const SEED_DRINKS: Drink[] = [
  // ---------- 와인 ----------
  d({
    id: "seed-wine-1",
    name_ko: "샤또 마고",
    name_en: "Château Margaux",
    category: "wine",
    sub_category: "red",
    producer: "Château Margaux",
    region: "보르도",
    country: "프랑스",
    vintage: 2015,
    abv: 13.5,
    description: "우아한 타닌과 긴 여운을 지닌 보르도 프리미엄 레드.",
    vivino_score: 4.7,
    vivino_count: 12450,
    flavor_tags: ["블랙커런트", "제비꽃", "우아한 타닌", "오크"],
  }),
  d({
    id: "seed-wine-2",
    name_ko: "클라우디 베이 소비뇽 블랑",
    name_en: "Cloudy Bay Sauvignon Blanc",
    category: "wine",
    sub_category: "white",
    producer: "Cloudy Bay",
    region: "말보로",
    country: "뉴질랜드",
    vintage: 2022,
    abv: 13.0,
    description: "상큼한 산도와 패션프루트 향이 특징인 화이트.",
    vivino_score: 4.2,
    vivino_count: 28900,
    flavor_tags: ["패션프루트", "라임", "허브", "높은 산도"],
  }),
  d({
    id: "seed-wine-3",
    name_ko: "모엣 샹동 임페리얼",
    name_en: "Moët & Chandon Impérial",
    category: "wine",
    sub_category: "sparkling",
    producer: "Moët & Chandon",
    region: "샹파뉴",
    country: "프랑스",
    vintage: null,
    abv: 12.0,
    description: "섬세한 버블과 청사과·시트러스 풍미의 대표 샴페인.",
    vivino_score: 4.1,
    vivino_count: 41200,
    flavor_tags: ["청사과", "브리오슈", "시트러스", "섬세한 버블"],
  }),

  // ---------- 위스키 ----------
  d({
    id: "seed-whisky-1",
    name_ko: "맥캘란 12년 셰리 오크",
    name_en: "The Macallan 12 Sherry Oak",
    category: "whisky",
    sub_category: "single_malt",
    producer: "The Macallan",
    region: "스페이사이드",
    country: "스코틀랜드",
    abv: 40.0,
    description: "셰리 캐스크 숙성의 건과일과 달콤한 오크 풍미.",
    vivino_score: 4.5,
    vivino_count: 8800,
    flavor_tags: ["건포도", "오크", "꿀", "스파이시"],
  }),
  d({
    id: "seed-whisky-2",
    name_ko: "라프로익 10년",
    name_en: "Laphroaig 10",
    category: "whisky",
    sub_category: "single_malt",
    producer: "Laphroaig",
    region: "아일라",
    country: "스코틀랜드",
    abv: 40.0,
    description: "강렬한 피트와 요오드, 바다 내음의 아일라 싱글몰트.",
    vivino_score: 4.4,
    vivino_count: 7600,
    flavor_tags: ["피트", "스모키", "요오드", "바다"],
  }),
  d({
    id: "seed-whisky-3",
    name_ko: "야마자키 12년",
    name_en: "Yamazaki 12",
    category: "whisky",
    sub_category: "single_malt",
    producer: "Suntory",
    region: "야마자키",
    country: "일본",
    abv: 43.0,
    description: "꿀과 과실, 미즈나라 오크의 섬세한 일본 위스키.",
    vivino_score: 4.6,
    vivino_count: 5400,
    flavor_tags: ["꿀", "복숭아", "미즈나라 오크", "부드러움"],
  }),

  // ---------- 맥주 ----------
  d({
    id: "seed-beer-1",
    name_ko: "구스 아일랜드 IPA",
    name_en: "Goose Island IPA",
    category: "beer",
    sub_category: "ipa",
    producer: "Goose Island",
    region: "시카고",
    country: "미국",
    abv: 5.9,
    description: "시트러스·솔향 홉이 두드러지는 균형 잡힌 IPA.",
    vivino_score: 3.8,
    vivino_count: 15200,
    flavor_tags: ["홉", "자몽", "솔향", "쌉쌀함"],
  }),
  d({
    id: "seed-beer-2",
    name_ko: "기네스 드래프트",
    name_en: "Guinness Draught",
    category: "beer",
    sub_category: "stout",
    producer: "Guinness",
    region: "더블린",
    country: "아일랜드",
    abv: 4.2,
    description: "로스팅 보리의 커피·초콜릿 풍미와 크리미한 질감.",
    vivino_score: 4.0,
    vivino_count: 33100,
    flavor_tags: ["커피", "초콜릿", "로스팅", "크리미"],
  }),

  // ---------- 사케 ----------
  d({
    id: "seed-sake-1",
    name_ko: "닷사이 23 준마이다이긴조",
    name_en: "Dassai 23 Junmai Daiginjo",
    category: "sake",
    sub_category: "junmai_daiginjo",
    producer: "Asahi Shuzo",
    region: "야마구치",
    country: "일본",
    abv: 16.0,
    description: "23%까지 정미한 화려한 과실향의 프리미엄 준마이다이긴조.",
    vivino_score: 4.5,
    vivino_count: 2100,
    flavor_tags: ["멜론", "배", "화이트플로럴", "깔끔함"],
  }),
  d({
    id: "seed-sake-2",
    name_ko: "쿠보타 만쥬",
    name_en: "Kubota Manju",
    category: "sake",
    sub_category: "junmai_daiginjo",
    producer: "Asahi Shuzo (Niigata)",
    region: "니가타",
    country: "일본",
    abv: 15.5,
    description: "부드럽고 우아한 감칠맛의 니가타 명주.",
    vivino_score: 4.3,
    vivino_count: 1500,
    flavor_tags: ["우마미", "쌀향", "부드러움", "은은함"],
  }),

  // ---------- 막걸리 ----------
  d({
    id: "seed-makgeolli-1",
    name_ko: "복순도가 손막걸리",
    name_en: "Boksoondoga",
    category: "makgeolli",
    sub_category: "premium",
    producer: "복순도가",
    region: "울산",
    country: "대한민국",
    abv: 6.5,
    description: "강한 탄산과 산뜻한 산미가 인상적인 프리미엄 막걸리.",
    vivino_score: 4.2,
    vivino_count: 980,
    flavor_tags: ["강한 탄산", "산뜻함", "쌀향", "샴페인 같은"],
  }),
  d({
    id: "seed-makgeolli-2",
    name_ko: "느린마을 막걸리",
    name_en: "Neurinmaeul",
    category: "makgeolli",
    sub_category: "premium",
    producer: "배상면주가",
    region: "경기",
    country: "대한민국",
    abv: 6.0,
    description: "무감미료, 부드러운 단맛과 곡물향의 생막걸리.",
    vivino_score: 4.0,
    vivino_count: 760,
    flavor_tags: ["부드러운 단맛", "곡물향", "무감미료", "묵직함"],
  }),
];
